Initial commit
linuxserver/docker-paperless-ngx pull request #1
Opened 2022-03-11 13:07 UTC by alex-phillips

2022-03-21 12:57 UTC, Roxedus approved these changes

2022-03-21 13:05 UTC, aptalca commented on jenkins-vars.yml
> +ls_branch: master
This needs to be `main`

2022-03-21 13:06 UTC, aptalca requested changes
See comment above

2022-03-21 16:43 UTC, aptalca approved these changes, later dismissed

2022-03-21 16:48 UTC, aptalca commented
Both arm logs have various errors

2022-03-24 12:45 UTC, alex-phillips commented
> Both arm logs have various errors

@aptalca could be a qemu issue. This same error existed in the old NG build logs and rox has confirmed on his hardware that it is working properly.

2022-03-24 12:47 UTC, darkmattercoder commented
I built it on my M1 using aarch64 and can confirm, that I do not see those errors. I am still trying to verify it on my raspberrypi for armhf.

2022-03-24 12:53 UTC, aptalca approved these changes

2022-03-24 12:54 UTC, merged